apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kafka-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: KafkaCluster is the Schema for the kafkaclusters API
      displayName: Kafka Cluster
      kind: KafkaCluster
      name: kafkaclusters.kafka.zncdata.dev
      version: v1alpha1
  description: kafka
  displayName: Kafka
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - hdfs
  - operator
  links:
  - name: Kafka Operator
    url: https://kafka-operator.domain
  maintainers:
  - email: lwpk110@163.com
    name: luwei
  maturity: alpha
  provider:
    name: zncdata-labs
    url: https://github.com/zncdata-labs/hdfs-operator
  version: 0.0.0
